version: 2

refs:
  - &only_master
    filters:
      branches:
        only:
          - master
  - &not_master:
    filters:
      branches:
        ignore:
          - master

jobs:
  all_build:
    steps:
      - setup
      - build
      - lint
      - test
  all_generate:
    steps:
      - setup
      - generate
      - lint
      - test
  master_build:
    steps:
      - setup
      - build
      - lint
      - test
      - release_package
  master_generate:
    steps:
      - setup
      - generate
      - lint
      - test
      - release_package

workflows:
  version: 2
  branches:
    jobs:
      - all:
          context: common-env-vars
          <<: *not_master
  release:
    jobs:
      - master:
          context: common-env-vars
          <<: *only_master

commands:
  setup:
    steps:
      - checkout
      - run:
          name: Versions
          command: node -v && npm -v && yarn -v
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - v1-yarn-node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  lint:
    steps:
      - run:
          name: Lint
          command: yarn lint
  test:
    steps:
      - run:
          name: Test
          command: yarn test
  build:
    steps:
      - run:
          name: Build
          command: yarn build
  generate:
    steps:
      - run:
          name: Build (Generate static app)
          command: yarn generate
  release_package:
    steps:
      - run:
          name: Release
          command: |
            npx semantic-release &&
            npx commit-status success Version "'\${PROJECT_VERSION}'"
